name: check_uno_size

on:
  push:
    branches:
      - master
    paths:
      - 'src/**'
      - 'examples/**'
      - 'ci/**'
      - '.github/workflows/**'
      - 'CMakeLists.txt'
      - 'platformio.ini'
      - 'library.json'
      - 'library.properties'
  pull_request_target:
    branches:
      - master
    paths:
      - 'src/**'
      - 'examples/**'
      - 'ci/**'
      - '.github/workflows/**'
      - 'CMakeLists.txt'
      - 'platformio.ini'
      - 'library.json'
      - 'library.properties'

jobs:
  build:
    uses: ./.github/workflows/build_template_binary_size.yml
    with:
      board: uno
      max_size: 11000
      max_size_apa102: 9300
  build_no_forced_inline:
    uses: ./.github/workflows/build_template_binary_size.yml
    with:
      board: uno
      max_size: -1
      max_size_apa102: -1
      extra_args: --defines FASTLED_NO_FORCE_INLINE
